# -*- coding: utf-8 -*-
"""IA Notebook #1 Regrecion Lineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pg12j8STOlXuWLeCMsY18zFWOJ1mjLcW
"""

import numpy as np
#import scipy as sc
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston

# cargamos la libreria
boston = load_boston()

print(boston.DESCR)

"""Formula minimizar el error cuadrático medio (MCD): $\beta = (X^(T)X)^(-1)X^(T)Y$"""

X = np.array(boston.data[:,5])
Y = np.array(boston.target)
#print(X)
#print(Y)

plt.scatter(X,Y, alpha=0.3)

#añadimos columnas de unos para termino independiente
X = np.array([np.ones(506),X]).T
#print(X)

B = np.linalg.inv((X.T @ X)) @ X.T @ Y

plt.plot([4,9],[B[0] + B[1] * 4, B[0] + B[1] * 9], c="red")

plt.show()

